version: "3"

services:
  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app

  flask:
    build: ./flask_app
    ports:
      - "5000"
    volumes:
      - ./flask_app:/app
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "2000:2000" # Map port 2000 inside the container to port 2000 on the host machine
      - "6000:6000" # Map port 6000 inside the container to port 6000 on the host machine
    volumes:
      - ./frontend:/app
    env_file:
      - .env
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kasun
      POSTGRES_PASSWORD: 123kasun
      POSTGRES_DB: fitnessdb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - flask
      - streamlit
      - frontend
