version: "3"

services:
  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app

  flask:
    build: ./flask_app
    ports:
      - "5000"
    volumes:
      - ./flask_app:/app
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/fit-demo-api.zero-one.online.crt:/etc/nginx/ssl/fit-demo-api.zero-one.online.crt:ro
      - ./nginx/fit-demo-api.zero-one.online.key:/etc/nginx/ssl/fit-demo-api.zero-one.online.key:ro
    depends_on:
      - flask
      - streamlit
