version: "3"

services:
  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app

  flask:
    build: ./flask_app
    ports:
      - "5000"
    volumes:
      - ./flask_app:/app
    env_file:
      - .env
