FROM nginx:latest
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY fit-demo-api.zero-one.online.crt /etc/nginx/ssl/yfit-demo-api.zero-one.online.crt
COPY fit-demo-api.zero-one.online.key /etc/nginx/ssl/fit-demo-api.zero-one.online.key